### ISSUE TITLE
Please add a license file to the repository root

### ISSUE THREAD

**Issue by bosenok** [wpnuxt/wpnuxt-core#197]
Hi there,

First of all, thank you for your work on this project! I noticed that the README indicates that this project is MIT licensed, but I didn’t see a corresponding LICENSE file in the root of the repository. Would you mind adding one to help clarify the licensing terms?

Having a clear and explicit license file makes it easier for everyone to understand the legal permissions and conditions for using, modifying, and redistributing the code.

Thank you so much for your time and for considering this request!

**Comment by vernaillen** [comment]
Thanks for highlighting this, @bosenok.

I added the LICENSE file
